
# This will appear before many messages from the plugin.
message-prefix: '&8[&3K&7N&8]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'a' 

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'

