main: wbs.extras.WbsExtras
name: WbsExtras
version: 1.0.0
api-version: 1.13
author: Weber588
description: A variety of configurable options for various servers 
commands:

#######################
#        STAFF        #
#######################

  lastcommand:
    description: View the last commands run by a specific user
    permission: wbsextras.staff.lastcommand
    aliases: [lastcmd]
  commandspy:
    description: Spy on specific commands or players without spamming chat
    permission: wbsextras.staff.commandspy
    aliases: [cmdspy]
  itemhistory:
    description: View the last item pick ups/drops run by a specific user
    permission: wbsextras.staff.itemhistory
    
#######################
#        CHAT         #
#######################
    
  notifications:
    description: Configure chat based notifications
    permission: wbsextras.chat.notif
    aliases: [notif, notification]
    
#######################
#        MISC         #
#######################

  signedit:
    description: Edit a sign after it is already written.
    permission: wbsextras.misc.signedit
    aliases: [editsign]
  colourbook:
    description: Fill in colour codes in a held written book.
    permission: wbsextras.misc.colourbook
    aliases: [colorbook, bookcolour, bookcolor]
  editbook:
    description: Unlock a written book to edit further.
    permission: wbsextras.misc.editbook
    aliases: [bookedit]
  nightvision:
    aliases: [nv]
    description: Add or remove permanent night vision from the player
    permission: wbsextras.misc.nightvision
  display:
    description: Change the appearance of the held item
    permission: wbsextras.misc.display
    
permissions:
  wbsextras.notif.*:
    description: Chat notification features
  
  wbsextras.colourbook:
    description: The ability to colour books signed by you.
    children:
      wbsextras.colourbook.other:
        description: The ability to colour books signed by others.
        
    
    
  wbsextras.signedit:
    description: Access to the /signedit command.
    children:
      wbsextras.signedit.looking:
        description: Change a sign by looking at it, bypassing any other restrictions placed on it by other plugins/protections.
    
  wbsextras.staff.*:
    description: All staff features
    children:
      wbsextras.staff.chat:
        description: The ability to use local staff chat.
      wbsextras.staff.lastcommand:
        description: Access to /lastcommand
        children:
          wbsextras.staff.lastcommand.exempt:
            description: Exemption from being tracked by /lastcommand
      wbsextras.staff.itemhistory:
        description: Access to /itemhistory
      wbsextras.staff.commandspy:
        description: Access to /commandspy.
        children:
          wbsextras.staff.commandspy.exempt:
            description: Users with this permission cannot be spyed on at all.
          wbsextras.staff.commandspy.ignore-blacklist:
            description: Users with this permission can spy on any command, even ones in the blacklist.
        