main: wbs.extras.WbsExtras
name: WbsExtras
version: 1.0.0
api-version: 1.13
author: Weber588
description: A variety of configurable options for various servers 
commands:
  lastcommand:
    description: View the last commands run by a specific user
    permission: wbsextras.staff.lastcommand
  itemhistory:
    description: View the last item pick ups/drops run by a specific user
    permission: wbsextras.staff.itemhistory
permissions:
  wbsextras.notif.*:
    description: Chat notification features
    
  wbsextras.staff.*:
    description: All staff features
    children:
      wbsextras.staff.chat:
        description: The ability to use local staff chat.
      wbsextras.staff.lastcommand:
        description: Access to /lastcommand
        children:
          wbsextras.staff.lastcommand.exempt:
            description: Exemption from being tracked by /lastcommand
      wbsextras.staff.itemhistory:
        description: Access to /itemhistory
      wbsextras.staff.commandspy:
        description: Access to /commandspy.
        children:
          wbsextras.staff.commandspy.exempt:
            description: Users with this permission cannot be spyed on at all.
          wbsextras.staff.commandspy.ignore-blacklist:
            description: Users with this permission can spy on any command, even ones in the blacklist.
        